#!/usr/bin/env python3
import sys, os

from pprint import pprint

from parse   import parse
from convert import convert
from plot    import plot

def main(args):
    data = dict()
    for filename in os.listdir('data'):
        filepath = 'data/' + filename
        data[filename] = parse(filepath)
    df = convert(data)
    plot(df)

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
