#!/usr/bin/env python3
import sys

from parse import parse
from pprint import pprint

def main(args):
    data = dict()
    for filename in args:
        data[filename] = parse(filename)
    pprint(data)

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
